### ISSUE TITLE
conversion breaks when JSON file has spaces in the name

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/xbundle#13]
For example, this file:

https://github.mit.edu/mitx/content-mit-801cc/blob/master/policies/2014_Fall/policy%20backup.json

**Comment by carsongee** [comment]
We shouldn't be grabbing these at all, the only two files that are anything but ignored by edX is `policy.json` and `grading_policy.json`, everything else is just random user added stuff.

**Comment by ichuang** [comment]
Agreed - we don't want to import such non-standard policy files.

**Comment by ShawnMilo** [comment]
@carsongee & @ichuang: Thanks. Please see updated fix.

**Comment by pdpinch** [comment]
@ichuang what about assets.json ? http://edx-open-learning-xml.readthedocs.org/en/latest/policies/assets-policy.html

I wouldn't expect xbundle to care much about static file metadata, but I don't know all the uses for it.

**Comment by ichuang** [comment]
Good point - yes, assets.json should be included in the xbundle.

The idea is that an xbundle + static files should be able to provide a
faithful reproduction of an entire (baseline, edX-platform) course.

Early on, this is exactly how the mitx platform worked - everything was
stored in a single XML file, plus static media files.
