### ISSUE TITLE
make it python 3 compatible

### ISSUE THREAD

**Issue by pdpinch** [mitodl/xbundle#30]

**Comment by ShawnMilo** [comment]
This is at least partially addressed by branch skm_lore. At least, it's enough to make LORE tests pass.

**Comment by pdpinch** [comment]
In that cast, @amir-qayyum-arbisoft please use https://github.com/mitodl/xbundle/tree/skm_lore as a starting point. You can start a new branch from it in your fork, test it, make any additions and then create a PR back to this repo.

**Comment by amir-qayyum-arbisoft** [comment]
yes sure @pdpinch

**Comment by pdpinch** [comment]
closed by #32
