### ISSUE TITLE
fails to completely convert 2.01

### ISSUE THREAD

**Issue by pdpinch** [mitodl/xbundle#43]
Trying to convert the course at https://github.mit.edu/mitx/content-mit-201-2015_Fall

xbundle is failing to include the content within verticals, for nearly all verticals. For example:

https://github.mit.edu/mitx/content-mit-201-2015_Fall/blob/master/chapter/Week_1.xml#L2-L4

is bundled as:

```
<course org="MITx" course="2.01r_2" url_name_orig="2015_Fall" semester="2015_Fall">
    <chapter display_name="Week 1" url_name_orig="Week_1">
      <sequential url_name="seq_WO1" display_name="Weekly Overview">
        <vertical url_name="WO1"/>
      </sequential>
```

-- ignoring the contents of https://github.mit.edu/mitx/content-mit-201-2015_Fall/blob/master/vertical/WO1.xml

This may be the same root cause of this bug https://github.com/mitodl/lore/issues/502

**Comment by ShawnMilo** [comment]
I don't have access to that course repository.

**Comment by pdpinch** [comment]
Argh. I missed this notification. You should have access now.

**Comment by pdpinch** [comment]
I think this bug is happening because xbundle assumes that vertical tags will only include references to other tags (i.e. `vertical` is in `DESCRIPTOR_TAGS`). 

In this course, the vertical file contains the content and no references to other files.

**Comment by jamiefolsom** [comment]
Documenting as I go. Removing ```vertical``` from ```DESCRIPTOR_TAGS``` makes no difference.

**Comment by jamiefolsom** [comment]
@pdpinch removing ```sequential``` (parent of ```vertical```) from ```DESCRIPTOR_TAGS``` fixes the problem. 

It reveals other issues; in particular: there were a couple of minor issues with the xml contained in the course verticals (missing close tag in one case; missing semicolon in another), which shouldn't cause the whole script to fail.

But at least, this appears to remove the issue which prevented the content from being pulled in from the vertical files. I'll work on a PR.

**Comment by pwilkins** [comment]
@jamiefolsom You may find a utility that @carsongee wrote useful.  https://github.com/mitodl/openedx-course-test is a utility that performs a health check on an edX course.  I find it useful to separate fact from fiction.  (and sometimes even fiction from fiction.)

**Comment by jamiefolsom** [comment]
@pwilkins thanks, I will have a look!
