### ISSUE TITLE
Create Dockerfile for testing

### ISSUE THREAD

**Issue by noisecapella** [mitodl/xbundle#46]
This is mostly a developer convenience to have a reproduceable testing environment for xbundle

**Comment by ShawnMilo** [comment]
I have been having trouble with running the tests. Many are failing, but some of it is definitely due to missing dependencies, both system-installed and pip-installable.

Do you have instructions for what must be done in order for `xbundle_convert test` to run for a new contributor?

**Comment by noisecapella** [comment]
I submitted a PR, in that branch you should be able to just run `docker-compose build` and then `docker-compose run xbundle` to run the tests. The PR includes the commits from the test framework PR
